version: '3.7'

services:
#  db:
#    image: mysql
#    restart: on-failure
#    environment:
#      MYSQL_ROOT_PASSWORD: ${DB_PASSWORD}
#      MYSQL_DATABASE: ${DB_NAME}
#    ports:
#      - "3306:3306"
#    volumes:
#      - ./data/mysql/:/var/lib/mysql
#  pma:
#    image: phpmyadmin/phpmyadmin
#    environment:
#      PMA_HOST: db
#      PMA_PORT: 3306
#      PMA_ARBITRARY: 1
#    restart: always
#    ports:
#      - "8081:80"
#    links:
#      - db
  admin:
    build:
      context: ./admin
      dockerfile: web.dockerfile
    ports:
      - "7777:8000"
    restart: on-failure
    volumes:
      - ./admin:/admin
    env_file:
      - .env
    command: >
      sh -c "python manage.py makemigrations &&
             python manage.py migrate &&
             python manage.py runserver 0.0.0.0:8000"
#    depends_on:
#      - db
#  bot:
#    build:
#      context: ./bot
#      dockerfile: bot.dockerfile
#    env_file:
#      - .env
#    restart: on-failure
#    depends_on:
#      - db
