# Generated by Django 4.2.3 on 2023-07-30 19:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('admin_web', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Oauth',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('tg_user_id', models.BigIntegerField(verbose_name='TG ID')),
                ('hash', models.CharField(max_length=1024, verbose_name='Хеш')),
                ('token', models.CharField(max_length=1024, verbose_name='Токен')),
                ('expired', models.DateTimeField(verbose_name='Истекает')),
            ],
            options={
                'verbose_name': 'Авторизация',
                'verbose_name_plural': 'Авторизации',
                'db_table': 'oauths',
                'managed': False,
            },
        ),
    ]
