# Generated by Django 4.2.3 on 2023-07-27 13:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('admin_web', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='tag',
            options={'managed': False, 'verbose_name': 'Тэг', 'verbose_name_plural': 'Тэги'},
        ),
    ]
